---
title: "Assignment 6"
format: 
  revealjs:
    transition: slide
---

## JSON Websites {.smaller}

Example: https://jsonplaceholder.typicode.com/

``` json
{
  "userId": 1,
  "title": "Sample title"
}
```

::::: columns
::: column
Structure & Composition:

-   Key-value pairs, lightweight

-   Nested objects and array

-   Easy to read and parase
:::

::: column
Technologies/Methods

-   REST APIs (data via HTTP requests)

-   JavaScript, AJAX (dynamic updates)

-   Used in three-tier web architecture (browser ↔ server ↔ database)
:::
:::::

## XML Website {.smaller}

Example: https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml

``` xml
<article>
  <title>Sample Title</title>
</article>
```

::::: columns
::: column
Structure & Composition:

-   Tag-based, hierarchical

-   Self-descriptive but verbose

-   Strict Syntax
:::

::: column
Technologies/Methods

-   SOAP web services (XML-based communication

-   JRSS feeds, enterprise systems

-   Server-side processing (JSP, PHP) generates XML/HTML
:::
:::::

## SQL Exercise

i

``` sql
SELECT s.ID
FROM student s
LEFT JOIN advisor a
  ON s.ID = a.s_id
WHERE a.i_id IS NULL;
```

ii

``` sql
SELECT i.ID, i.name
FROM instructor i
JOIN teaches t ON i.ID = t.ID
JOIN course c ON c.course_id = t.course_id
WHERE c.dept_name = i.dept_name
GROUP BY i.ID, i.name
HAVING COUNT(DISTINCT t.course_id) = (
    SELECT COUNT(*)
    FROM course c2
    WHERE c2.dept_name = i.dept_name
)
ORDER BY i.name;
```

## R and PostgreSQL {.smaller}

(a) Simple query: fetch all rows/columns in 'instructor' and create a data object

    ``` R
         id           name   dept_name    salary
    1 63395       McKinnon Cybernetics  94333.99
    2 78699          Pingr  Statistics  59303.62
    3 96895           Mird   Marketing 119921.41
    4  4233            Luo     English  88791.45
    5  4034         Murata   Athletics  61387.56
    6 50885 Konstantinides   Languages  32570.50
    ```

(b) Another query: fetch instructors in 'Comp. Sci.' department

    ``` R
         id     name  dept_name    salary
    1 34175    Bondi Comp. Sci. 115469.11
    2  3335 Bourrier Comp. Sci.  80797.83
    ```

<!-- -->

(c) Query a different table, e.g., 'student', and store in an R dataframe

``` R
    id       name  dept_name tot_cred
1 79352      Rumat    Finance      100
2 76672     Miliko Statistics      116
3 14182 Moszkowski Civil Eng.       73
4 44985     Prieto    Biology       91
5 44271    Sowerby    English      108
6 40897    Coppens       Math       58
```
